#location of your webserver, hosting controller.php
controllerphppath = 'http://192.168.50.40/controller.php'
#if the enviroment is set correctly this should be fine, otherwise use absolute path here
database = './controller.db'
#please ensure chrome is installed and the correct directory set here
chromepath = '/usr/bin/google-chrome'

batteryvoltagediv = 'body > div:nth-child(1)'
targetvoltagediv = 'body > div:nth-child(2)'
chargingcurrentdiv = 'body > div:nth-child(3)'
arrayvoltagediv = 'body > div:nth-child(4)'
arraycurrentdiv = 'body > div:nth-child(5)'
outputpowerdiv = 'body > div:nth-child(6)'
sweepvmpdiv = 'body > div:nth-child(7)'
sweepvocdiv = 'body > div:nth-child(8)'
sweeppmaxdiv = 'body > div:nth-child(9)'
batterytempdiv = 'body > div:nth-child(10)'
controllertempdiv = 'body > div:nth-child(11)'
killowatthoursdiv = 'body > div:nth-child(12)'
controllerstatusdiv = 'body > div:nth-child(13)'
controllerabsorptiondiv = 'body > div:nth-child(14)'
controllerbalancediv = 'body > div:nth-child(15)'
controllerfloatdiv = 'body > div:nth-child(16)'
maxenergydailydiv = 'body > div:nth-child(17)'
amperehoursdailydiv = 'body > div:nth-child(18)'
watthoursdailydiv = 'body > div:nth-child(19)'
maxvoltagedailydiv = 'body > div:nth-child(20)'
maxbatteryvoltagedailydiv = 'body > div:nth-child(21)'
minbatteryvoltagedailydiv = 'body > div:nth-child(22)'
inputpowerdiv = 'body > div:nth-child(23)'
ledstatusdiv = 'body > div:nth-child(24)'
batterypolesvoltagediv = 'body > div:nth-child(25)'
batterysensorvoltagediv = 'body > div:nth-child(26)'